### ISSUE TITLE
ConfigUpdate throws NPE on KV nested keys.

### ISSUE THREAD

**Issue by onmomo** [Magnetme/consultant#32]
as soon as a key has been created in the KV store for the registered service without a value, consultant starts throwing NullPointerExceptions repeatedly:

consultant version: 1.7.4
consul version: 1.0.2

```
2018-01-05T14:27:37,426Z ERROR [pool-1-thread-1]         me.magnet.consultant.ConfigUpdater       - Error occurred while retrieving/publishing new config from Consul: null
java.lang.NullPointerException: null
	at java.util.Base64$Decoder.decode(Base64.java:549) ~[na:1.8.0_121]
	at me.magnet.consultant.ConfigUpdater.updateConfig(ConfigUpdater.java:172) ~[consultant-1.7.4.jar:na]
	at me.magnet.consultant.ConfigUpdater.run(ConfigUpdater.java:105) ~[consultant-1.7.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

The config response for my KV is:

```
[
    {
        "LockIndex": 0,
        "Key": "config/phoenix-app-local/networks/network01",
        "Flags": 0,
        "Value": "MTIz",
        "CreateIndex": 19,
        "ModifyIndex": 24
    },
    {
        "LockIndex": 0,
        "Key": "config/phoenix-app-local/networks/network02",
        "Flags": 0,
        "Value": "YWJjCmNkZQ==",
        "CreateIndex": 21,
        "ModifyIndex": 21
    },
    {
        "LockIndex": 0,
        "Key": "config/phoenix-app-local/failing-key",
        "Flags": 0,
        "Value": null,
        "CreateIndex": 26,
        "ModifyIndex": 26
    }
]
```

Means the issue occurs for keys which don't have a value set "config/phoenix-app-local/failing-key"

**Comment by michaeldejong** [comment]
Hi @onmomo. Thanks for the bug report. I'll take a look at it 👍

**Comment by onmomo** [comment]
@michaeldejong your welcome, I updated the ticket tested with a old consul version. Seems like with the latest version nested keys / folders aren't returned any longer but the issue for keys without a values still persists.

**Comment by michaeldejong** [comment]
@onmomo I pushed a fix to Maven Central which should ignore keys with no value (version 1.7.5). Mind you it might take a couple hours before it actually becomes available on Maven Central. Please try it out and let us know if that fixes the problem.

> Seems like with the latest version nested keys / folders aren't returned any longer...

AFAIK we never returned config located in nested folders inside the config folder for the services (ie. `/<possible-config-prefix>/<service-name>/<some-folder>/<key>`). I'm not really sure how we'd even represent that in the `Properties` object reliably. /<possible-config-prefix>/<service-name>/<key>` should work though. Let us know you have a use case for this.

Again, thanks for the bug report!

**Comment by onmomo** [comment]
@michaeldejong thank for this very fast fix, works! Having keys in nested folders works with consultant since consul returns them in the same format as non nested keys.
 Keys that represent a folder aren't returned any longer with consul 1.0.2

**Comment by michaeldejong** [comment]
Ah I see, so the key would be something like `<folder>/<key>`. I'm not entirely sure that works correctly with `Properties`, but it's worth a shot if that's how devs/ops like to organize their config. I think it might have worked by accident in 1.0.2, as we didn't really intend for it to be used like that. I might have some time next week to take a look at this.

**Comment by onmomo** [comment]
What doesn't work is listening on changes on the node / folder for children key changes with the SettingListener. As a workaround, the ConfigListener can be used, which returns the full config changes
